### PR TITLE
Ensure parker metrics are required correctly

### PR DESCRIPTION
**Pull request by tanem**
Walking to `../node_modules/` broke things for me using npm 3.

### CODE REVIEW

**Comment by bdefore** [comment]
thanks @tanem that fixes things for me

**Comment by tanem** [comment]
Cool, no worries @bdefore :+1:

**Comment by leny** [comment]
Hi, thanks for the PR (and sorry for the long wait).
I've just merged and publish your modifications as version `0.1.4`.

**Comment by tanem** [comment]
No worries, thanks @leny :+1:

**Pull request merged**
